# Generated by Django 4.1.5 on 2023-01-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_alter_sight_id'),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='sights',
            field=models.ManyToManyField(to='sights.sight'),
        ),
    ]
