# Generated by Django 4.1.5 on 2023-01-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
